/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao;
import controle.ControleUsuario;
import entidades.Usuario;
import java.awt.Color;
import java.awt.Component;
import java.awt.Window;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author Paulo Victor
 */
public class CadastroUsuario extends javax.swing.JPanel {
    ControleUsuario todosControleUsuario = new ControleUsuario();
    Usuario usuarioLogado;
    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario(Usuario usuarioEditar) {
        initComponents();
        jButtonCadastro.setText("Editar");
        jTextFieldLogin.setText(usuarioEditar.getLogin());
        jTextFieldNome.setText(usuarioEditar.getNome());
        usuarioLogado = usuarioEditar;
        idUsuario.setText(Integer.toString(usuarioEditar.getId()));
    }
    public CadastroUsuario() {
        initComponents();
        idUsuario.setVisible(false);
        jLabelidd.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldNome = new javax.swing.JTextField();
        jLabelNome = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jPasswordSenha = new javax.swing.JPasswordField();
        jLabelSenha = new javax.swing.JLabel();
        jTextFieldLogin = new javax.swing.JTextField();
        jButtonCadastro = new javax.swing.JButton();
        idUsuario = new javax.swing.JLabel();
        jLabelidd = new javax.swing.JLabel();

        jLabelNome.setText("Nome");

        jLabelLogin.setText("Login");

        jLabelSenha.setText("Senha");

        jButtonCadastro.setText("Cadastro");
        jButtonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroActionPerformed(evt);
            }
        });

        idUsuario.setText("jLabel1");

        jLabelidd.setText("Id:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabelSenha)
                                .addComponent(jLabelLogin)
                                .addComponent(jLabelNome)
                                .addComponent(jTextFieldNome)
                                .addComponent(jPasswordSenha)
                                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jButtonCadastro))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabelidd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idUsuario)))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idUsuario)
                    .addComponent(jLabelidd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonCadastro)
                .addContainerGap(81, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroActionPerformed
            boolean nomeValidado = false;
            boolean loginValidado = false;
            boolean senhaValidada = false;
            String nome = jTextFieldNome.getText();
            String login = jTextFieldLogin.getText();
            String senha = jPasswordSenha.getText();
            if(nome.length()>=6 && !nome.isEmpty()){
                jLabelNome.setForeground(Color.BLACK);
                nomeValidado = true;
            }else{
                jLabelNome.setForeground(Color.red);
            }if(login.length()>=6 && !nome.isEmpty()){
               jLabelLogin.setForeground(Color.BLACK);
               loginValidado = true;
            }else{
                jLabelLogin.setForeground(Color.red);
            }if(senha.length()>=6 && !senha.isEmpty()){
               jLabelSenha.setForeground(Color.BLACK);
               senhaValidada = true;
            }else{
                jLabelSenha.setForeground(Color.red);
            }
               if(senhaValidada && loginValidado && nomeValidado){
                   if(jButtonCadastro.getText().equals("Cadastro")){
                        if(todosControleUsuario.cadastroUsuario(nome, login, senha)){
                            JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                            Component comp = SwingUtilities.getRoot(this);
                            ((Window) comp).dispose();
                        }else{
                            JOptionPane.showMessageDialog(null, "Um usuario já existe com esse login!", "Erro", JOptionPane.YES_OPTION);
                        }  
                   }else if(jButtonCadastro.getText().equals("Editar")){
                       if(todosControleUsuario.editarUsuario(nome, login, senha, usuarioLogado.getId())){
                            JOptionPane.showMessageDialog(null, "Usuario editado com sucesso!!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                            Component comp = SwingUtilities.getRoot(this);
                            ((Window) comp).dispose();
                            TelaInicial novo = new TelaInicial();
                            JframePrincipal jf  = new JframePrincipal(novo);
                            jf.setResizable(false);
                            
                        }else{
                            JOptionPane.showMessageDialog(null, "Um usuario já existe com esse login!", "Erro", JOptionPane.YES_OPTION);
                        }  
                   }
                        
               }else{
                   JOptionPane.showMessageDialog(null, "campos em vermelho devem ter mais de 6 caracteres!!", "Erro quantidade de caracteres!!!", JOptionPane.YES_OPTION);
               }
    }//GEN-LAST:event_jButtonCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel idUsuario;
    private javax.swing.JButton jButtonCadastro;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelidd;
    private javax.swing.JPasswordField jPasswordSenha;
    private javax.swing.JTextField jTextFieldLogin;
    private javax.swing.JTextField jTextFieldNome;
    // End of variables declaration//GEN-END:variables
}
